# Generated by Django 4.2.7 on 2024-07-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.IntegerField(verbose_name='Код ошибки')),
                ('error_description', models.CharField(default='', max_length=100, verbose_name='Описание ошибки')),
                ('url', models.URLField(verbose_name='Ссылка, на которой возникла ошибка')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время записи ошибки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='front_errors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог ошибки с фронтенда',
                'verbose_name_plural': 'Логи ошибок с фронтенда',
                'ordering': ['-created_at'],
            },
        ),
    ]
